[homebrew.shared]
taps = []
brews = [
    "bat",
    "bottom",
    "chezmoi",
    "eza",
    "fd",
    "fzf",
    "gcc",
    "gemini-cli",
    "gh",
    "ghq",
    "jq",
    "lazygit",
    "mise",
    "neovim",
    "ripgrep",
    "starship",
    "yq",
    "zellij",
    "zoxide"
]
casks = []

[homebrew.work]
taps = []
brews = [
    "awscli",
    "azure-cli",
    "git-secret",
    "lima",
    "colima"
]
casks = [
    "copilot-cli",
    "firefox",
    "font-fira-code-nerd-font",
    "font-hackgen-nerd",
    "font-moralerspace",
    "gcloud-cli",
    "karabiner-elements",
    "raycast",
    "rectangle",
    "visual-studio-code",
    "wezterm"
]

[homebrew.private]
taps = ["anomalyco/tap"]
brews = ["anomalyco/tap/opencode"]
casks = []
