[homebrew.shared]
taps = []
brews = [
    "bat",
    "bottom",
    "chezmoi",
    "eza",
    "fd",
    "fzf",
    "gcc",
    "gh",
    "ghq",
    "jq",
    "lazygit",
    "mise",
    "neovim",
    "ripgrep",
    "starship",
    "yq",
    "zellij",
    "zoxide",
]
casks = [
    "copilot-cli",
]
gui_casks = []

[homebrew.work]
taps = []
brews = [
    "awscli",
    "azure-cli",
    "git-secret",
    "lima",
    "colima",
]
casks = [
    "claude-code",
    "codex",
    "gcloud-cli",
]
gui_casks = [
    "firefox",
    "font-fira-code-nerd-font",
    "font-hackgen-nerd",
    "font-moralerspace",
    "karabiner-elements",
    "raycast",
    "rectangle",
    "visual-studio-code",
    "wezterm",
]

[homebrew.private]
taps = [
    "anomalyco/tap",
]
brews = [
    "gemini-cli",
    "anomalyco/tap/opencode",
]
casks = []
gui_casks = []
